BEGIN;


CREATE TABLE IF NOT EXISTS "PE3" ("id" INT, PRIMARY KEY ("id"));


CREATE TABLE IF NOT EXISTS "PE4" ("id" INT, PRIMARY KEY ("id"));


CREATE TABLE IF NOT EXISTS "PE4" ("id" INT, PRIMARY KEY ("id"));


CREATE TABLE IF NOT EXISTS "PE1" ("id" INT, PRIMARY KEY ("id"));


CREATE TABLE IF NOT EXISTS "PE2" ("id" INT, PRIMARY KEY ("id"));


ALTER TABLE "PE4"
ADD CONSTRAINT "FK_PE4_PE3" FOREIGN KEY ("id") REFERENCES "PE3" ("id");


ALTER TABLE "PE3"
ADD CONSTRAINT "FK_PE3_PE2" FOREIGN KEY ("id") REFERENCES "PE2" ("id");


ALTER TABLE "PE2"
ADD CONSTRAINT "FK_PE2_PE1" FOREIGN KEY ("id") REFERENCES "PE1" ("id");


ALTER TABLE "PE3"
ADD CONSTRAINT "FK_PE3_PE4" FOREIGN KEY ("id") REFERENCES "PE4" ("id");


ALTER TABLE "PE4"
ADD CONSTRAINT "FK_PE4_PE1" FOREIGN KEY ("id") REFERENCES "PE1" ("id");


ALTER TABLE "PE4"
ADD CONSTRAINT "FK_PE4_PE2" FOREIGN KEY ("id") REFERENCES "PE2" ("id");


ALTER TABLE "PE1"
ADD CONSTRAINT "FK_PE1_PE2" FOREIGN KEY ("id") REFERENCES "PE2" ("id");


ALTER TABLE "PE4"
ADD CONSTRAINT "FK_PE4_PE2_2" FOREIGN KEY ("id") REFERENCES "PE2" ("id");


ALTER TABLE "PE1"
ADD CONSTRAINT "FK_PE1_PE3" FOREIGN KEY ("id") REFERENCES "PE3" ("id");


ALTER TABLE "PE3"
ADD CONSTRAINT "FK_PE3_PE3" FOREIGN KEY ("id") REFERENCES "PE3" ("id");


COMMIT;