BEGIN;


CREATE TABLE IF NOT EXISTS "pe1" ("id" INT, PRIMARY KEY ("id"));


CREATE TABLE IF NOT EXISTS "PE1" ("id" INT);


ALTER TABLE "PE1"
ADD CONSTRAINT "FK_PE1_pe1" FOREIGN KEY ("id") REFERENCES "pe1" ("id");


COMMIT;